#!/bin/bash

# Termux Whisper Share Integration Setup
# Creates the hook for Android's "Share" menu.

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

TERMUX_BIN="$HOME/bin"
HOOK_FILE="$TERMUX_BIN/termux-file-editor"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRANSCRIBE_SCRIPT="${PROJECT_DIR}/transcribe.sh"

echo -e "${BLUE}=== Android Share Integration ===${NC}"

# 1. Create bin directory if missing
if [ ! -d "$TERMUX_BIN" ]; then
    echo -e "${YELLOW}Creating ~/bin directory...${NC}"
    mkdir -p "$TERMUX_BIN"
fi

# 2. Check for existing hook
if [ -f "$HOOK_FILE" ]; then
    # Check if it's already ours
    if grep -q "Termux Whisper" "$HOOK_FILE"; then
        echo -e "${GREEN}Integration already active.${NC}"
        read -p "Press Enter to exit..."
        exit 0
    fi
    
    echo -e "${YELLOW}[WARN] Existing file editor hook found.${NC}"
    echo -e "Backing up to: ${HOOK_FILE}.bak"
    mv "$HOOK_FILE" "${HOOK_FILE}.bak"
fi

# 3. Create the Hook Script
echo -e "${YELLOW}Installing hook...${NC}"

cat << EOF > "$HOOK_FILE"
#!/bin/bash
# Termux Whisper Hook
# Generated by enable_share.sh

INPUT_FILE="\$1"

if [ -z "\$INPUT_FILE" ]; then
    echo "Error: No file received."
    read -p "Press Enter to exit..."
    exit 1
fi

# Launch Termux Whisper
# We use 'exec' to replace this process
bash "${TRANSCRIBE_SCRIPT}" "\$INPUT_FILE"

echo ""
read -p "Process complete. Press Enter to close..."
EOF

chmod +x "$HOOK_FILE"

echo -e "${GREEN}[SUCCESS] Integration enabled!${NC}"
echo -e "You can now share audio files from other apps to 'Termux'."
echo ""
read -p "Press Enter to return..."
