#!/bin/bash

# Termux Whisper Unified Dashboard
# Text-based CLI for easy access to all features.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRANS_SCRIPT="${SCRIPT_DIR}/core/transcribe.sh"
MODELS_SCRIPT="${SCRIPT_DIR}/core/models.sh"
CONFIG_FILE="$HOME/.termux_whisper_config"

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Load Config
if [ ! -f "$CONFIG_FILE" ]; then
    echo "DEFAULT_LANG=auto" > "$CONFIG_FILE"
fi
source "$CONFIG_FILE"

print_header() {
    clear
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}       Termux Whisper Dashboard         ${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo -e "${GREEN}Tip: Share audio from any app to 'Termux' to transcribe!${NC}"
}

print_menu() {
    echo -e "\n${YELLOW}Choose an action:${NC}"
    echo -e "  ${GREEN}1)${NC} Transcribe File (System Picker)"
    echo -e "  ${GREEN}2)${NC} Manage Models"
    echo -e "  ${GREEN}3)${NC} Quick Settings"
    echo -e "  ${GREEN}4)${NC} Help / About"
    echo -e "  ${RED}q)${NC} Exit"
    echo ""
}

set_language() {
    echo -e "\n${BLUE}--- Set Default Language ---${NC}"
    echo "Current: ${DEFAULT_LANG}"
    echo "Enter language code (e.g., 'en', 'es', 'fr', 'auto'):"
    read -p "> " lang_input

    if [ -n "$lang_input" ]; then
        if grep -q "DEFAULT_LANG=" "$CONFIG_FILE"; then
            sed -i "s/DEFAULT_LANG=.*/DEFAULT_LANG=$lang_input/" "$CONFIG_FILE"
        else
            echo "DEFAULT_LANG=$lang_input" >> "$CONFIG_FILE"
        fi
        DEFAULT_LANG="$lang_input"
        echo -e "${GREEN}Language set to: $lang_input${NC}"
    else
        echo -e "${YELLOW}Cancelled.${NC}"
    fi
    read -p "Press Enter to return..." dummy
}

toggle_share() {
    local TERMUX_BIN="$HOME/bin"
    local HOOK_FILE="$TERMUX_BIN/termux-file-editor"
    local DISABLED_HOOK="$TERMUX_BIN/termux-file-editor.disabled"

    echo -e "\n${BLUE}--- Android Share Integration ---${NC}"

    # Check current status
    if [ -f "$HOOK_FILE" ] && grep -q "Termux Whisper" "$HOOK_FILE"; then
        # Currently Enabled -> Disable
        mv "$HOOK_FILE" "$DISABLED_HOOK"
        echo -e "${YELLOW}Integration Disabled.${NC}"
        echo "The 'Share to Termux' feature is now turned off."
    elif [ -f "$DISABLED_HOOK" ] && grep -q "Termux Whisper" "$DISABLED_HOOK"; then
        # Currently Disabled -> Enable
        mv "$DISABLED_HOOK" "$HOOK_FILE"
        chmod +x "$HOOK_FILE"
        echo -e "${GREEN}Integration Enabled.${NC}"
        echo "You can now share files to Termux again."
    else
        # Missing -> Create
        echo "Hook file missing. Recreating..."
        mkdir -p "$TERMUX_BIN"
        cat << EOF > "$HOOK_FILE"
#!/bin/bash
# Termux Whisper Hook
# Generated by menu.sh

INPUT_FILE="\$1"

if [ -z "\$INPUT_FILE" ]; then
    echo "Error: No file received."
    read -p "Press Enter to exit..."
    exit 1
fi

# Launch Termux Whisper
bash "${TRANS_SCRIPT}" "\$INPUT_FILE"

echo ""
read -p "Process complete. Press Enter to close..."
EOF
        chmod +x "$HOOK_FILE"
        echo -e "${GREEN}Integration Created & Enabled.${NC}"
    fi
    read -p "Press Enter to return..." dummy
}

settings_menu() {
    local TERMUX_BIN="$HOME/bin"
    local HOOK_FILE="$TERMUX_BIN/termux-file-editor"

    while true; do
        source "$CONFIG_FILE"
        
        # Check Share Status
        local SHARE_STATUS="${RED}Disabled${NC}"
        if [ -f "$HOOK_FILE" ] && grep -q "Termux Whisper" "$HOOK_FILE"; then
            SHARE_STATUS="${GREEN}Enabled${NC}"
        fi

        echo -e "\n${BLUE}--- Quick Settings ---${NC}"
        echo -e "  1) Set Default Language [Current: ${DEFAULT_LANG}]"
        echo -e "  2) Android Share Integration [$SHARE_STATUS]"
        echo -e "     ${YELLOW}(Allows sharing audio directly to Termux from other apps)${NC}"
        echo -e "  3) View Config File"
        echo -e "  b) Back"
        echo ""
        read -p "Select: " opt
        case $opt in
            1) set_language ;;
            2) toggle_share ;;
            3) 
                echo -e "\n${YELLOW}--- $CONFIG_FILE ---${NC}"
                cat "$CONFIG_FILE"
                echo -e "${YELLOW}--------------------------${NC}"
                read -p "Press Enter to return..." dummy
                ;;
            b|B) return ;;
            *) echo -e "${RED}Invalid option.${NC}" ;;
        esac
    done
}

show_help() {
    echo -e "\n${BLUE}--- About Termux Whisper ---${NC}"
    echo "A high-performance wrapper for whisper.cpp."
    echo ""
    echo -e "${YELLOW}Transcripts saved to:${NC}"
    echo "/sdcard/Download/Termux-Whisper/"
    echo ""
    echo "Developed for Termux."
    read -p "Press Enter to return..." dummy
}

# Main Loop
print_header
while true; do
    print_menu
    read -p "Select option: " selection
    
    case $selection in
        1) bash "$TRANS_SCRIPT" --file-picker ;; 
        2) bash "$MODELS_SCRIPT" ;; 
        3) settings_menu ;; 
        4) show_help ;;
        q|Q) 
            echo "Bye!"
            exit 0 
            ;;
        *) 
            echo -e "${RED}Invalid selection.${NC}" 
            ;;
    esac
done
